// When request is nil, internal error is returned.
{nil, ErrInternalError},
for _, testCase := range testCases {
t.Fatalf("Unexpected s3error returned wanted %d, got %d", testCase.s3Error, s3Error)